FROM python:3

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/django
COPY requirements.txt ./
RUN pip install -r requirements.txt

EXPOSE 8000